### ISSUE TITLE
Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException

### ISSUE THREAD

**Issue by spottedmahn** [luminous-software/developer-news#2]
### Installed product versions
- Visual Studio: 2019 Preview (16.2.0 Preview 1)
- This extension: 1.4

### Description

![image](https://user-images.githubusercontent.com/14079228/58709793-ead30680-8388-11e9-8a1e-9518cba8ea24.png)

>5/31/2019 9:41:43 AM - Skipping 'C:\Users\mdepouw\AppData\Local\Microsoft SDKs' as it doesn't exist
5/31/2019 9:41:43 AM - Beginning to install extension to Microsoft Visual Studio Enterprise 2019...
5/31/2019 9:41:43 AM - Upgrading 'Extensibility Logs', version 1.4 to version 1.5.0.
5/31/2019 9:41:44 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.CoreEditor (Microsoft.VisualStudio.Component.CoreEditor)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsixComponent, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

### Steps to recreate
1. Upgrade from 1.4 to 1.5 in VS 2019 Preview

### Current behavior
Install error

### Expected behavior
No exeception 😊

**Comment by yannduran** [comment]
I'm sorry you're having a problem with v1.5's upgrade. It's midnight here in Australia right now, so I'll have a look into this tomorrow and let you know what I find.

Thanks for letting me know about this!

**Comment by yannduran** [comment]
I was just having a quick look before I went to bed, and realised that you meant _Extensibility Tools v1.5_, not _Developer News_ which has only one version (v1.0). You've added your bug report to the wrong repo. Did one of my links send you here? Or did you find the repo yourself?

Same deal though, I'll look into it tomorrow. Could you open the issue in the [_Extensibility Tools_ repo], that way the issue will still be instigated by yourself. I I do it it'll look like I created the issue myself. :-)

Thanks!

**Comment by spottedmahn** [comment]
>You've actually added your bug report to the wrong repo

It felt wrong but I just followed the links 😊

![image](https://user-images.githubusercontent.com/14079228/58712518-b82c0c80-838e-11e9-9ab4-53d37468492c.png)

![image](https://user-images.githubusercontent.com/14079228/58712548-c7ab5580-838e-11e9-8867-286bbf3e2e6d.png)

**Comment by spottedmahn** [comment]
>Same deal though, I'll look into it tomorrow.

no rush!

>Could you open the issue in the Extensibility Logs repo

np, will do

**Comment by spottedmahn** [comment]
https://github.com/luminous-software/extensibility-logs/issues/8

**Comment by yannduran** [comment]
v1.5.1 has been uploaded,which should fix the installation problem. Please let me know if you have any more problems :-)
